server:
  port: 9000

spring:
  application:
    name: penny-save-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    poolName: penny-save-pool
    maximum-pool-size: 10
    minimum-idle: 0
    idle-timeout: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: false