app:
  email:
    from: contato@pennysave.com
    name: Penny Save
    subject: Penny Save - Confirme Sua Conta
    link: http://localhost:9000/penny-save

spring:
  mail:
    host: 127.0.0.1
    port: 3025
    username: penny-save-mail
    password: mailpassword
    protocol: smtp