name: Penny Save Continuous Integration

on: 
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Clean
      run: ./gradlew clean
    - name: Build
      run: ./gradlew build -x test
    - name: Test
      run: ./gradlew test
